name: Conventional commits

on: pull_request

jobs:
  check-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we need all the history to be able to resolve revision ranges properly
          fetch-depth: 0
      - name: Install commitizen
        run: python -m pip install commitizen
      - name: Run commit message checks
        run: |
          echo cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
